### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by zoomself** [fynv/ScoreDraft#1]
how to install?

**Comment by fynv** [comment]
Hi, thanks for contact.
What OS are you using? If you are using Windows x64 or Linux amd64, then the "python_test" directory is ready to use after download. You just need to install Python 3.
For other OS, you need to build from source-code. It's easy because I'm using CMake here. The only thing need to say is, set "CMAKE_INSTALL_PREFIX" to the "python_test"  directory. 
File issues here if you get compilation issues.

**Comment by zoomself** [comment]
ok,thanks

**Comment by fynv** [comment]
Closing
